language: php

sudo: false

matrix:
  include:
    - php: 7.4
    - php: 8.0
    - php: 8.1

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then composer test -- --coverage-text --coverage-clover=coverage.clover; else composer test -- --no-coverage; fi

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
